############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Portfolio"
url = "/portfolio"
weight = 3

[[main]]
name = "Recognition"
url = "/recognition"
weight = 4

[[main]]
name = "Giving Back"
url = "/giving-back"
weight = 5

[[main]]
name = "Media"
weight = 6

[[main]]
parent = "Media"
name = "Podcasts"
url = "/media/podcasts"

[[main]]
name = "Contact"
url = "/contact"
weight = 7

# footer menu
[[footer]]
name = "Portfolio"
url = "/portfolio"
weight = 2

[[footer]]
name = "Recognition"
url = "/recognition"
weight = 3

[[footer]]
name = "Giving Back"
url = "/giving-back"
weight = 4

[[footer]]
name = "Media"
url = "/media/podcasts"
weight = 5

[[footer]]
name = "Contact"
url = "/contact"
weight = 6